'use strict';

const TARGET_CATALOG = [
  { id: 'codex-desktop', name: 'Codex Desktop', surface: 'desktop', mode: 'provider-routed', windows: 'native', homepage: 'https://openai.com/codex/', docs: 'https://developers.openai.com/codex/app/', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false },
  { id: 'codex-cli', name: 'Codex CLI', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://github.com/openai/codex', docs: 'https://developers.openai.com/codex/cli/', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@openai/codex'], package: '@openai/codex' }] },
  { id: 'opencode-cli', name: 'OpenCode', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://opencode.ai/', docs: 'https://opencode.ai/docs/', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', 'opencode-ai'], package: 'opencode-ai' }] },
  { id: 'aider-cli', name: 'Aider', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://aider.chat/', docs: 'https://aider.chat/docs/install.html', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'uv', command: 'uv.exe', args: ['tool', 'install', '--force', 'aider-chat'], package: 'aider-chat' }] },
  { id: 'claude-cli', name: 'Claude Code', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://www.anthropic.com/claude-code', docs: 'https://docs.anthropic.com/en/docs/claude-code/setup', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@anthropic-ai/claude-code'], package: '@anthropic-ai/claude-code' }] },
  { id: 'claude-app', name: 'Claude Desktop', surface: 'desktop', mode: 'provider-routed', windows: 'native', homepage: 'https://claude.ai/download', docs: 'https://support.anthropic.com/', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false },
  { id: 'pi-cli', name: 'Pi Coding Agent', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://github.com/badlogic/pi-mono', docs: 'https://github.com/badlogic/pi-mono/tree/main/packages/coding-agent', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@mariozechner/pi-coding-agent'], package: '@mariozechner/pi-coding-agent' }] },
  { id: 'cline-cli', name: 'Cline CLI', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://cline.bot/', docs: 'https://docs.cline.bot/cli/cli-reference', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@cline/cli'], package: '@cline/cli' }] },
  { id: 'dsh-cli', name: 'DeepSeek Harness Web', surface: 'web-cli', mode: 'provider-routed', windows: 'native', homepage: 'https://github.com/deepseek-ai/DeepSeek-Harness', docs: 'https://github.com/deepseek-ai/DeepSeek-Harness', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false },
  { id: 'hermes-cli', name: 'Hermes Agent', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://github.com/NousResearch/hermes-agent', docs: 'https://github.com/NousResearch/hermes-agent', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false },
  { id: 'gemini-cli', name: 'Gemini CLI', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://github.com/google-gemini/gemini-cli', docs: 'https://github.com/google-gemini/gemini-cli/blob/main/docs/get-started/installation.md', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@google/gemini-cli'], package: '@google/gemini-cli' }] },
  { id: 'vscode-app', name: 'Visual Studio Code', surface: 'desktop', mode: 'workspace-only', windows: 'native', homepage: 'https://code.visualstudio.com/', docs: 'https://code.visualstudio.com/docs', implementation: 'implemented', verificationStatus: 'unverified', vendorLogin: false, install: [{ type: 'winget', command: 'winget.exe', args: ['install', '--exact', '--id', 'Microsoft.VisualStudioCode', '--accept-package-agreements', '--accept-source-agreements'], package: 'Microsoft.VisualStudioCode' }] },

  { id: 'crush-cli', name: 'Crush', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://github.com/charmbracelet/crush', docs: 'https://github.com/charmbracelet/crush/blob/main/docs/config/README.md', implementation: 'implemented', verificationStatus: 'verified', vendorLogin: false, install: [{ type: 'winget', command: 'winget.exe', args: ['install', '--exact', '--id', 'charmbracelet.crush', '--accept-package-agreements', '--accept-source-agreements'], package: 'charmbracelet.crush' }, { type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@charmland/crush'], package: '@charmland/crush' }] },
  { id: 'qwen-cli', name: 'Qwen Code', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://github.com/QwenLM/qwen-code', docs: 'https://qwenlm.github.io/qwen-code-docs/en/users/configuration/model-providers/', implementation: 'implemented', verificationStatus: 'verified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@qwen-code/qwen-code@latest'], package: '@qwen-code/qwen-code' }] },
  { id: 'kilo-cli', name: 'Kilo Code CLI', surface: 'cli', mode: 'provider-routed', windows: 'native', homepage: 'https://kilocode.ai/', docs: 'https://github.com/Kilo-Org/kilocode/blob/main/packages/kilo-docs/pages/code-with-ai/platforms/cli.md', implementation: 'implemented', verificationStatus: 'verified', vendorLogin: false, install: [{ type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@kilocode/cli'], package: '@kilocode/cli' }] },

  { id: 'copilot-cli', name: 'GitHub Copilot CLI', surface: 'cli', mode: 'native-account', windows: 'native', homepage: 'https://github.com/features/copilot/cli', docs: 'https://docs.github.com/en/copilot/how-tos/copilot-cli/set-up-copilot-cli/install-copilot-cli', implementation: 'cataloged', verificationStatus: 'unverified', vendorLogin: true, install: [{ type: 'winget', command: 'winget.exe', args: ['install', '--exact', '--id', 'GitHub.Copilot', '--accept-package-agreements', '--accept-source-agreements'], package: 'GitHub.Copilot' }, { type: 'npm', command: 'npm.cmd', args: ['install', '-g', '@github/copilot'], package: '@github/copilot' }] },

];

const TARGET_CATALOG_BY_ID = new Map(TARGET_CATALOG.map((target) => [target.id, target]));

function catalogTarget(id) { return TARGET_CATALOG_BY_ID.get(id) || null; }

module.exports = { TARGET_CATALOG, TARGET_CATALOG_BY_ID, catalogTarget };
